# Generated by Django 5.2.3 on 2025-06-24 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_comment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='authorUser',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='commentPost',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='dataCreation',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='postCategory',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='category',
            new_name='categoryThrough',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='post',
            new_name='postThrough',
        ),
        migrations.RemoveField(
            model_name='author',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
        migrations.AddField(
            model_name='author',
            name='ratingAuthor',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='userPost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('ARTICLE', 'Article'), ('NEWS', 'News')], default='ARTICLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
