# Generated by Django 5.2.3 on 2025-06-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='news',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
